const LANGUAGE_LABEL_MAP = {
  abap: 'ABAP',
  actionscript: 'ActionScript',
  ada: 'Ada',
  adb: 'ADB',
  angular: 'Angular Template',
  apex: 'Apex',
  apl: 'APL',
  applescript: 'AppleScript',
  asm: 'Assembly',
  astro: 'Astro',
  awk: 'Awk',
  bash: 'Bash',
  bat: 'Batch',
  batch: 'Batch',
  beancount: 'Beancount',
  bibtex: 'BibTeX',
  bicep: 'Bicep',
  blade: 'Blade',
  c: 'C',
  cjs: 'JavaScript',
  clj: 'Clojure',
  clojure: 'Clojure',
  cljs: 'ClojureScript',
  cobol: 'COBOL',
  codeowners: 'CODEOWNERS',
  coffeescript: 'CoffeeScript',
  conf: 'Config',
  config: 'Config',
  cpp: 'C++',
  csharp: 'C#',
  cson: 'CSON',
  css: 'CSS',
  csv: 'CSV',
  cue: 'Cue',
  cxx: 'C++',
  cypher: 'Cypher',
  dart: 'Dart',
  docker: 'Dockerfile',
  dockerfile: 'Dockerfile',
  dotenv: '.env',
  ejs: 'EJS',
  elixir: 'Elixir',
  elm: 'Elm',
  erb: 'ERB',
  erl: 'Erlang',
  erlang: 'Erlang',
  fsharp: 'F#',
  fish: 'Fish',
  fs: 'F#',
  gdscript: 'GDScript',
  gherkin: 'Gherkin',
  git: 'Git',
  gitcommit: 'Git Commit',
  gitignore: 'Git Ignore',
  gleam: 'Gleam',
  glsl: 'GLSL',
  gnuplot: 'Gnuplot',
  go: 'Go',
  gql: 'GraphQL',
  graphql: 'GraphQL',
  groovy: 'Groovy',
  h: 'C Header',
  handlebars: 'Handlebars',
  haskell: 'Haskell',
  hbs: 'Handlebars',
  hcl: 'HCL',
  hpp: 'C++ Header',
  htm: 'HTML',
  html: 'HTML',
  ini: 'INI',
  java: 'Java',
  javascript: 'JavaScript',
  jinja: 'Jinja',
  jinja2: 'Jinja2',
  jl: 'Julia',
  json: 'JSON',
  json5: 'JSON5',
  jsonc: 'JSONC',
  jsx: 'JSX',
  julia: 'Julia',
  kotlin: 'Kotlin',
  kql: 'KQL',
  kt: 'Kotlin',
  kts: 'Kotlin Script',
  latex: 'LaTeX',
  less: 'Less',
  liquid: 'Liquid',
  lisp: 'Lisp',
  log: 'Log',
  logo: 'Logo',
  lua: 'Lua',
  make: 'Makefile',
  makefile: 'Makefile',
  markdown: 'Markdown',
  md: 'Markdown',
  mdx: 'MDX',
  mermaid: 'Mermaid',
  mjs: 'JavaScript',
  move: 'Move',
  nginx: 'Nginx',
  nim: 'Nim',
  nix: 'Nix',
  nushell: 'Nushell',
  objc: 'Objective-C',
  objectivec: 'Objective-C',
  ocaml: 'OCaml',
  pascal: 'Pascal',
  perl: 'Perl',
  php: 'PHP',
  pl: 'Perl',
  plaintext: 'Text',
  postcss: 'PostCSS',
  powershell: 'PowerShell',
  prisma: 'Prisma',
  proto: 'Protocol Buffers',
  protobuf: 'Protocol Buffers',
  ps1: 'PowerShell',
  pug: 'Pug',
  py: 'Python',
  python: 'Python',
  r: 'R',
  rb: 'Ruby',
  reason: 'ReasonML',
  regex: 'Regex',
  rel: 'Rel',
  rst: 'reStructuredText',
  rs: 'Rust',
  ruby: 'Ruby',
  rust: 'Rust',
  sass: 'Sass',
  scala: 'Scala',
  scss: 'SCSS',
  shell: 'Shell',
  sh: 'Shell',
  solidity: 'Solidity',
  sql: 'SQL',
  sqlite: 'SQLite',
  svelte: 'Svelte',
  swift: 'Swift',
  systemd: 'systemd',
  tcl: 'Tcl',
  tex: 'TeX',
  text: 'Text',
  toml: 'TOML',
  ts: 'TypeScript',
  tsv: 'TSV',
  tsx: 'TSX',
  twig: 'Twig',
  typescript: 'TypeScript',
  vb: 'Visual Basic',
  vbnet: 'Visual Basic .NET',
  vue: 'Vue',
  wat: 'WebAssembly Text',
  wasm: 'WebAssembly',
  xml: 'XML',
  xsl: 'XSLT',
  yaml: 'YAML',
  yml: 'YAML',
  zig: 'Zig',
  zsh: 'Zsh',
  'c#': 'C#',
  'c++': 'C++',
  'f#': 'F#',
  'objective-c': 'Objective-C',
  'objective-cpp': 'Objective-C++',
};

function humanizeUnknownLanguage(value: string) {
  return value
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) =>
      part.length <= 3 ? part.toUpperCase() : part.charAt(0).toUpperCase() + part.slice(1)
    )
    .join(' ');
}

export function getLanguageLabel(language = '') {
  const normalized = String(language)
    .toLowerCase()
    .trim()
    .replace(/^language-/, '');
  if (!normalized) return '';

  const compact = normalized.replace(/\s+/g, '');
  return (
    LANGUAGE_LABEL_MAP[normalized as keyof typeof LANGUAGE_LABEL_MAP] ??
    LANGUAGE_LABEL_MAP[compact as keyof typeof LANGUAGE_LABEL_MAP] ??
    humanizeUnknownLanguage(normalized)
  );
}
